apiVersion: v1
kind: Service
metadata:
  labels:
    app: flask-test
  name: web
spec:
  ports:
    - nodePort: 30500
      port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    app: flask-test
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask
  labels:
    app: flask-test
spec:
  replicas: 3
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: flask-test
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: flask-test
    spec:
      containers:
        - name: flask
          image: rusovandrey/flask-app:v1
          ports:
            - containerPort: 5000
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 3